// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX0GgooXDDf4qzmNS0GCtAZS_vHe5Zx5E',
    appId: '1:127570866822:web:bc66d6e47218ba6c8a5707',
    messagingSenderId: '127570866822',
    projectId: 'trendy-threads-26c7e',
    authDomain: 'trendy-threads-26c7e.firebaseapp.com',
    storageBucket: 'trendy-threads-26c7e.firebasestorage.app',
    measurementId: 'G-RMFV7R23GJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgM0REMY8qGKjFwTyr9sIQ91GN6LIrjbQ',
    appId: '1:127570866822:android:90226d128a8063898a5707',
    messagingSenderId: '127570866822',
    projectId: 'trendy-threads-26c7e',
    storageBucket: 'trendy-threads-26c7e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKRfNARA5sYE6ZGU0md2kJEL75hm1vZ3E',
    appId: '1:127570866822:ios:c1c795770be02c248a5707',
    messagingSenderId: '127570866822',
    projectId: 'trendy-threads-26c7e',
    storageBucket: 'trendy-threads-26c7e.firebasestorage.app',
    iosClientId: '127570866822-q4vpnshiedessq0qe0ph9t4hj8l5ub3s.apps.googleusercontent.com',
    iosBundleId: 'com.example.trendyThreads',
  );

}